### ISSUE TITLE
showpageafterlogin not working at all?

### ISSUE THREAD

**Issue by alimat-nz** [s-blu/showpageafterlogin#2]
I am using Greebo and have installed the plugin via plugin manager, but it does not seem to be doing anything. I can specify a page and a number int he configuration settings, but this never seems to be executed. i have tried with both a 'start' page and 'wiki:faq' - both of which exist - and with number set to 0 and 9999 again with no luck. Any ideas whether I am missing something or whether the plugin is really compatible with the version of dokuwiki?

**Comment by umbomas** [comment]
**+1**

Same for me, the plugin does not seem to work at all. Just for information: I am playing with a "Dokuwiki on a Stick" installation.

**Comment by umbomas** [comment]
**Update.**

After some debugging I discovered:
- the plugin is registered,
- the **handle_redirect** method looks for the value $event->data['preact'] == 'login'
- ...but when called, $event->data['preact'] is equal to 'redirect'
So currently **handle_redirect** is a do-nothing.

Changing the condition in $event->data['preact'] == 'redirect', the plugin works as expected. 

I have too few experience with Dokuwiki code and PHP, so I don't know if the event 'redirect' is triggered only after login. I fear that this simple change could trigger also undesired redirections.

Anyone can help?

**Comment by s-blu** [comment]
Hey @alimat-nz, I'm very sorry for the very late answer. I finally came around to have a look. 

What @umbomas discovered is absolutely right, but I also was not able to pinpoint where the redirect action is called and what this change may cause. I ran some click tests I could think of and it seems like things are working as expected, so I decided to push the changes, so that the plugin should be useable again.

I had a look what could cause these change and found out that a new action dispatcher was introduced in Greebo, like stated here: https://www.dokuwiki.org/changes#release_2018-04-22a_release_greebo . I guess this is related.

Maybe I am able to find some additional informations here, but if not I'll leave the change as is. I'd highly appreciate reports if this causes unwanted behaviour and I try my best to fix those then a lot faster.

**Comment by alimat-nz** [comment]
Thanks - all working now :)
 
 
----- Original message -----From: Sam <notifications@github.com>To: s-blu/showpageafterlogin <showpageafterlogin@noreply.github.com>Cc: alimat-nz <amatthew@nz1.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [s-blu/showpageafterlogin] showpageafterlogin not working at all? (#2)Date: Wed, Jan 9, 2019 11:58 PM 
Hey @alimat-nz, I'm very sorry for the very late answer. I finally came around to have a look.
What @umbomas discovered is absolutely right, but I also was not able to pinpoint where the redirect action is called and what this change may cause. I ran some click tests I could think of and it seems like things are working as expected, so I decided to push the changes, so that the plugin should be useable again.
I had a look what could cause these change and found out that a new action dispatcher was introduced in Greebo, like stated here: https://www.dokuwiki.org/changes#release_2018-04-22a_release_greebo . I guess this is related.
Maybe I am able to find some additional informations here, but if not I'll leave the change as is. I'd highly appreciate reports if this causes unwanted behaviour and I try my best to fix those then a lot faster.
